### ISSUE TITLE
Couldn't find MCP9808 ...

### ISSUE THREAD

**Issue by ReckBr** [ncguk/HUZZAH-MCP9808-Web-Server#1]
Hi thank you for this nice project, very useful for a beginner like me...

I don't know why but my MCP9808 can't be found at the default address 0x18, 
so I had to add it in your sketch (Line 83) : 
`if (!tempsensor.begin(0x18)) {`
`    Serial.println("Couldn't find sensor!");`
`    while (1);`
`    }`

It's obviouly NOT an bug in your sketch but I think there is a mistake in the 
"_Adafruit MCP9808  Library_" **V1.1.0** (new version i think)

Maybe you can add it ? just to be sure and avoiding other people lose time to understand why it does'nt work. even if the code is correct...

Sorry for my bad english... and Thanks again

Console feedback before adding the address : 
> Connected to BrWiFiP
IP address: 10.2.0.13
mDNS responder started
HTTP server started
Couldn't find sensor!

> Soft WDT reset

> ###stack###
ctx: cont
sp: 3ffffdc0 end: 3fffffc0 offset: 01b0
3fffff70:  00000000 00000000 00000000 40202bf0  
3fffff80:  00000000 00000000 00000000 feefeffe  
3fffff90:  feefeffe feefeffe feefeffe 3ffeedbc  
3fffffa0:  3fffdad0 00000000 3ffeed8c 4020cba0  
3fffffb0:  feefeffe feefeffe 3ffe851c 401009bd  
###stack###

**Comment by ncguk** [comment]
First of all, apologies for not dealing with this issue sooner. GitHub didn't give me any alert or indication that you had posted an issue, and I've only spotted it today by accident, while updating the sketch to work with the latest ESP8266 libraries.

I've made the change you suggest. Adafruit's MCP9808 example sketch code also explicitly adds the i2C address to the begin statement, and I suspect this is because the MCP9808 can be chained together and use one of eight i2c addresses.

And your English is just fine 👍 .
